# Generated by Django 3.0.5 on 2020-04-27 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista_host', '0002_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 27, 16, 4, 1, 912769)),
        ),
    ]
