# Generated by Django 3.0.5 on 2020-04-27 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('revista_host', '0003_auto_20200427_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 27, 13, 5, 0, 400766, tzinfo=utc)),
        ),
    ]
